services:
  playit_gateway:
    container_name: playit_gateway
    image: donalberton/playit_gateway:latest
    ports:
      - 8000:80
    env_file:
      - ./playit_api_gateway/.env
    environment:
      - PLAYIT_URL_BASE=http://playit_api
      - CLASSIFIER_URL_BASE=http://classifier
      - SCHEDULER_URL_BASE=http://scheduler
    build: ./playit_api_gateway
    networks:
      - backend

  playit_api:
    container_name: playit_api
    image: donalberton/playit_api:latest
    # ports:
    #   - 8080:80
    env_file:
      - ./playit_api/.env
    environment:
      - SPOTIFY_API_URL=https://api.spotify.com/v1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: ./playit_api
    networks:
      - backend

  classifier:
    container_name: classifier
    image: donalberton/classifier:latest
    # ports:
    #   - 8081:80
    env_file:
      - ./classifier/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PLAYIT_URL_BASE=http://playit_api
    build: ./classifier
    networks:
      - backend

  scheduler:
    container_name: scheduler
    image: donalberton/scheduler:latest
    # ports:
    #   - 8082:80
    env_file:
      - ./scheduler/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PLAYIT_URL_BASE=http://playit_api
    build: ./scheduler
    networks:
      - backend

  redis:
    container_name: redis
    image: redis
    # ports:
    #   - 6379:6379
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
